project:
  type: website
  output-dir: docs

website:
  title: "Transformers and Perception"
  navbar:
    left:
      - text: "Posts"
        href: posts/index.qmd

format:
  html:
    theme: cosmo
    toc: true